### ISSUE TITLE
Allow for Smooth Scroll to be sitewide

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-north#169]
I've had a number of confused people ask me recently why the smooth scroll only works for menu links and not links elsewhere. Obviously, this is due to the setting being a navigation setting. I however don't think it should be this way and that it should instead be a global setting. This way users who have internal links elsewhere on the page act in a consistent method.

**Comment by Misplon** [comment]
Since we have this as a Customizer setting it makes sense to expand the scope to be global.

**Comment by davidk132** [comment]
As a heads up, the extension of smooth scroll sitewide (#173) specifically creates a conflict with [Livemesh's SiteOrigin Widgets](http://portfoliotheme.org/siteorigin-widgets/tabs-and-accordions/), in particular the tabs widget (LSOW_Tabs) and any other widget that depends on anchors.

Because LSOW_Tabs identifies each tab with an anchor, the click event that switches between tabs is blocked by the `smoothScroll` method in `north.js`, which uses the CSS selector `'a[href*="#"]:not([href="#"])'` to grab every anchor on the page. As a result, clicking on a tab just scrolls the page up and down randomly, and does not expose the newly selected tab. On my site I cannot use LSOW_Tabs with SO North's Smooth Scroll, so I disabled Smooth Scroll (in the Customizer) in order to keep the tabs.

[More detail here](https://wordpress.org/support/topic/so-tabs-stopped-working-related-to-wp-46-update). Either SO North would need to update Smooth Scroll to account for third-party widgets' use of anchors, or Livemesh would need to update LSOW_Tabs to identify each tab by a means other than anchors. Or, Smooth Scroll would need to be disabled in order for the tabs to work.

**Comment by Misplon** [comment]
Thanks @davidk132, appreciate the effort. We'll pick this up ASAP in #200 and look to resolve in the next update.

**Comment by gregpriday** [comment]
Awesome. Thanks for the report @davidk132 - we'll get this resolved.
