### ISSUE TITLE
WooCommerce: Page settings on Shop and other pages

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-north#181]
Can we get page settings, specifically "No Sidebar" working on the Shop and other WooCommerce pages? What would it take?

**Comment by adiraomj** [comment]
@Misplon this issue should be posted in the setting framework repo.

**Comment by knightknight** [comment]
I've used the Page Template Settings > Type: Products, to set my 'No Sidebar' but where I've used 'Overlap Content' for Menu Settings and as a site wide design this becomes a problem. WooCommerces Shop page doesn't pick up anything built with Page Builder nor is there a way of putting a header image in via the customiser or something similar.

**Comment by Misplon** [comment]
Hi @knightknight 

**Overlap**
_but where I've used 'Overlap Content' for Menu Settings and as a site wide design this becomes a problem._

What problem do you run into?

**Shop**
The shop page is like your blog page, once assigned in WooCommerce settings, content from the editor isn't used. My guess is that the best way to proceed would be to build your own shop home page, different to the shop home page you assign in WooCommerce settings and then link to that page as your shop home in your menu.

**Header**
North doesn't support a header image via the Customizer that I know of so, unfortunately, that isn't an option.

**Comment by knightknight** [comment]
@Misplon, there is a similar issue on the SiteOrigin [https://siteorigin.com/thread/changing-default-woocommerce-shop-page/](url) thread about this. I've tried linking to an alternative shop page but the url will also resolve to /shop which can look odd if you pushing /store url.

That said I looked into the WooCommerce Shop template docs and found I needed to remove the `woocommerce_content();` from woocommerce.php and rebuild using WooCommerces template files as reference. That way I'm still able to use North's settings on the modified child version of woocommerce.php.

However the problem was where I've used 'Overlap Content' throughout the site with a transparent css color on the navigation. To keep everything consistent I've set from Page Template Settings > Type: Products > Menu Postion 'Overlap Content', but because there is no content between the masthead and woocommerce, woocommerce's content sits under the navigation menu. Similar to what was happening here:

![Image](https://s11.postimg.org/cp7m6m96b/pb-woo-02.jpg)

The work around I found for WooCommerce was to create a seperate header-woo.php and in woocommerce.php reference that instead. I then hard coded the image to that header file.

What would be better is if under 'Type: Products' you could upload an image or add some padding to WooCommerce's content... although this still doesn't address the issue if you've set a transparent color for the navigation.

* Shop Page: Set Header Image [ upload box ] (or grab featured image with additional ‘default, full width options to the output).
* Product Pages: Use featured image [ check box ] (with additional ‘default, full width options to the output)
* Adding top padding to WooCommerce content: px/%
* Also registering a seperate sidebar for WooCommerce rather then be restricted to using the main sidebar.

Anyway apart from the hard coding I've got it working with 'Overlap' so it remains consistent through the site. It was just frustrating to have used Page Builder up until I added WooCommerce that Page Builder then becomes useless for the Shop page.

**Comment by Misplon** [comment]
Thanks for the detailed feedback, I appreciate it.

Can you confirm that you're using a child theme for these modifications?

**Comment by knightknight** [comment]
I'm using a child theme for these changes. North relies on the 'catch all' woocommerce php snippet file so no point changing the parent theme files. Hopefully I should get some time and I'll try adding in my suggestions to the customise settings file.

**Comment by Misplon** [comment]
Ok awesome, glad to hear all the extra effort is update safe. Thanks again for your input. This has certainly come up before. With the Blog home page issue (as an example) we recommend users don't assign a posts page and instead build their own blog home using Page Builder and the Post Loops widget. I'll dive into ways we can accommodate the Shop home page and the overlap issue ASAP. Thanks again for the effort.
