### ISSUE TITLE
Smooth scroll: prevent conflict with third-party plugins

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-north#200]
@adiraomj Let's see what we can do with regards to the below bug report. First prize would be to focus our application of smooth scroll to generally prevent conflicts. Second prize would be to just deal with the Livemesh conflict.

**Bug report as follows:**

https://github.com/siteorigin/siteorigin-north/issues/169

davidk132 commented 5 hours ago
As a heads up, the extension of smooth scroll sitewide (#173) specifically creates a conflict with Livemesh's SiteOrigin Widgets, in particular the tabs widget (LSOW_Tabs) and any other widget that depends on anchors.

Because LSOW_Tabs identifies each tab with an anchor, the click event that switches between tabs is blocked by the smoothScroll method in north.js, which uses the CSS selector 'a[href*="#"]:not([href="#"])' to grab every anchor on the page. As a result, clicking on a tab just scrolls the page up and down randomly, and does not expose the newly selected tab. On my site I cannot use LSOW_Tabs with SO North's Smooth Scroll, so I disabled Smooth Scroll (in the Customizer) in order to keep the tabs.

More detail here. Either SO North would need to update Smooth Scroll to account for third-party widgets' use of anchors, or Livemesh would need to update LSOW_Tabs to identify each tab by a means other than anchors. Or, Smooth Scroll would need to be disabled in order for the tabs to work.

**Comment by davidk132** [comment]
Here are two options, both of which isolate the Smooth Scroll function and ignore other third-party methods that use anchors. They both work, however I recommend the second one which is more developer- and writer-friendly.

1.
The first idea is not very elegant, which is to prepend anchors with something like `#SOSS_{my-anchor-name-here}`, for example:

```
<a href="#SOSS_stuff">Link to more stuff</a>
```

and then look for that prepended tag in a CSS selector like this: `'a[href^="#SOSS_"]'`.

This ignores Livemesh tabs and any other widgets using their own anchors because they will not have the prepended string. It is not pretty because it complicates the URL and is bad for branding and marketing communications.

2.
For the second idea, add a class name to each link (outside of the navbar) and apply smooth scrolling where that class is found. In `north.js` I invented the class "soss" and changed the jQuery on line 381 to read like this:

```
$( '#site-navigation a[href^="#"]:not([href="#"])' ).add( 'a[href^="#"].soss' ).northSmoothScroll();
```

This also means that you can designate some anchor links to smooth scroll while excluding others. Any anchor link without the class "soss" will not smooth scroll. The HTML looks like this:

```
<a href="#stuff" class="soss">Link to more stuff</a>
```

To make it easier for site writers, the "add link" button on the edit post WYSIWYG could include a checkbox for opting out of smooth scroll. As long as the writer stays opted-in, the WYSIWYG would listen for an anchor link symbol `"#"` and automatically insert `class="soss"` behind the scenes.

Feel free to grab this code if you like, or else I can pop it into `north.js` as a PR.

**Comment by Misplon** [comment]
Awesome :) Thanks for the effort, it's most appreciated. We'll get into this ASAP!

**Comment by adiraomj** [comment]
The second solution that @davidk132  suggests is nice.

However, we should consider a couple of points. 

1. we would be restricting ourselves to the WYSIWYG editor only, which should not be much of a problem. 
2. We should consider backward compatibility.

**Comment by Misplon** [comment]
We've put off the decision for a bit by just excluding LiveMesh Tabs: https://github.com/siteorigin/siteorigin-north/pull/206. Will address again at a later stage (soon). Thanks everyone.

**Comment by Misplon** [comment]
The current exclusions seem to be working for now so I'll close this. If any further issues arise we can re-open it.
