### ISSUE TITLE
Main Menu: Change drop-down menu direction once viewport edge is reached

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-north#227]
If the viewport edge is reached, change the drop-down menu direction from right to left.

If we're in a second level drop-down and onwards, then I'm not quite sure how that would work as we'd already have drop-downs open going right. We could position drop-down items crossing the viewport below the last item in view. Ideas here welcome.

**Comment by adiraomj** [comment]
Wondering why this change would be needed? I'm guessing from  a UX point of view, most users would be more comfortable with the way things are.

If the issue is concerning dropdowns appearing beyond the viewport, users who have multiple levels of dropdowns for their first menu item would face a problem with this change. 

I think it would be better for users to design the menu to suit the theme and make good use of the menu breakpoint setting.

**Comment by Misplon** [comment]
Slack chat summary: Adi will try a very basic implementation of this, we'll see how it comes out.

**Comment by Misplon** [comment]
Going to close this for now due to overall workload.
