### ISSUE TITLE
A few bugs to report

### ISSUE THREAD

**Issue by frontenddevguy** [siteorigin/siteorigin-north#320]
1.)
Sometimes the rich textwidget is stripping paragraph tags, whether they are present in text view or not. This makes styling more specificity-dependent.

2.)
on a new row, with all fields blank for CSS, the frontend is still outputting inline padding and margin, which forces me to add !important rules.

3.) When Inked Blog is selected as a block, the standard page header (it is enabled) as well as a block containing header (before blog) shows nothing on the frontend. I tried all ways except hardcoding in a template file as the header/title does not show up

4.) Flexbox stretch setting for equal height columns not working. Can be seen on homepage, at the top. Currently I am setting heights to overcome the issue.

5.) Heavy flash of unstyled content from blog posts carousel. posts all shown as full width list before carousel kicks in (also on home page). Is this expected? I would have thought this would be ajax loading.. (going to look at plugins, which seem to deal only with images, or using something like jquery.lazy - any advice or recommendations welcome!)

**Comment by frontenddevguy** [comment]
The support thread over on siteorigin.com didnt allow me to comment for some reason.

Here is a screenshot: https://imgur.com/a/8xjCG that also shows the inline styles. Also here, no values are set in the 'design' section.

Seems wp went from adding <p> tags unnecessarily to everything to removing them from everything then. Sure enough <p> tags are missing from everything except footer textwidget. Hopefully Gutenberg will sort this out.

Here's a wip site: http://tictocsing.wpshala.com/

**Comment by AlexGStapleton** [comment]
Hi frontenddevguy,

Sorry for the delay - I didn't see this until now. Please note that these issues aren't directly related to SiteOrigin Noth (although 3 may be indirectly related). Regardless...

1. To confirm, what widget are you using? Also, can you please provide me with example HTML that's getting stripped?

2. The provided screenshot suggests an altered row layout which means that the inline CSS makes sense. Are you setting a non-standard Row Layout such as Full Width or Full Width Stretch?

3. I'm going to be honest, I'm not too sure what you mean. Can you please walk me through the exact steps you're taking?

4. Widgets aren't automatically stretched, the cell is. If you would like for a background color or image to stretch the entire length of a cell, you'll need to apply it to the cell directly rather than adding it via a widget.

To do this please open the relevant row and click the relevant row (click the blue area, and don't click the column size or you'll trigger a cell resize). Head over to the styles sidebar and head down to **Cell # Styles Sidebar**. Open the Design settings group and set the background as desired.

5. Expected, and sadly unavoidable as we cannot break the container (for full width, and full width stretched row layouts) until the DOM is ready.

**Comment by frontenddevguy** [comment]
I had to prioritise getting the site live, and starting another one.
It's live here (still needs a bit of optimisation for load/performance):
https://tictocsing.com/

1.) That was with rich text editor (text) widget. <p> tags were being stripped. The screenshot shows it.

2.) I specified full width, but no margin or padding in any of the fields.
I would say that expected functionality is that those styles would only be output at all if specified.
Any other styles relating to displaying a full width row of course would be output, although wouldn't it make more sense to just have everything attached to the full width class? In that case no need for inline styles unless the user chooses to design their site through Page Builder, rather than writing their own CSS.

3.) I am using Inked blog widget to display blog posts. A Site Origin post loop also had the same result, which is that no content before the loop was being output. That includes widget title or a row with header. The html is not being created for anything before the loop in that page.

4.) I'm not sure exactly why this wasn't working but in the end I added flex rules to all parent elements to get this to work. I was setting it on the row.

5.) I will be writing my own Js function or using a JQuery plugin to deal with this once I have enough time. It's a common requirement and plugins don't seem to handle it in any specific or useful enough way. One that I tried caused fitvids to stop working for example.

6.) I found a bug where the video carousel was continuing to play previous video in the background while still cycling through. I ended up ditching this for the widget that plays a single video and loads on click (with image placeholder). The 3 youtube videos in a carousel were several mb and not sensible to use without lazy loading (even without the strange background play behaviour).
It would be great to have a carousel that uses placeholder images rather than directly loading all the youtube scripts and assets to the page.

Hope some of that helps. I will add some of the relevant scenarios back to my staging site as soon as I have a bit of time, so you can see what's going on.

**Comment by AlexGStapleton** [comment]
1. TinyMCE will remove any instances of <p> without a class attached. This is sadly avoidable and if you wish to manually add paragraphs (without a class), you'll need to use something like the Custom HTML widget or not switch mode (which is what triggers the replacement in the text widget). This sadly was intentionally done by WordPress.

2. The margin and padding are automatically generated by us to break the theme container (using margin_ and to add the content container back (using padding). The inline styles are added as this is done on a case by case basis as not all rows are set up the same - while they generally are, this was done specifically like this for better general theme compatibility. If users wish to add additional horizontal margin or padding they should either apply it to the widget itself.

3. Can you please link me to a page where I can see this (without any adjustments you've made to bypass this)?

5. Plugins need to focus on high levels of general compatibility which is why things like this are typically avoided. I know it's not desired it's sadly unavoidable (for us).

6. Can you please clarify the name of the widget this is in regards to? I ask because we don't have a video carousel widget.

**Comment by frontenddevguy** [comment]
Hi, unfortunately I am into the next project with a tight deadline so no time for adding test cases to staging right now.. I will do it soon.

1.) and 2.) - Understood. Nothing that can't be worked around or that affects performance anyway.

Video carousel would probably have been Livemesh. I will contact them about it.

I found one more bug, which is with SO slider. It outputs an image even when only background image is selected. For now I will have to display: none the images.
Also I am finding that SO widgets don't allow access to custom image sizes, where the default text editor does.

**Comment by frontenddevguy** [comment]
And trying to add this shortcode in text widget:
[related_posts_by_tax]
works

[related_posts_by_tax format="thumbnails" image_size="medium"]
renders nothing

This is for 'Related Posts by Taxonomy' plugin

Some problem with quotes in shortcodes?

**Comment by AlexGStapleton** [comment]
Regarding the slider image output, can you please link me to a page where I can inspect this?

Regarding the shortcodes, no, there are no issues (that we're aware of) with using quotes in the shortcode so the issue you're facing isn't related to that. Can you please try replicating this issue in the SiteOrigin Editor widget with Automatically add Paragraphs disabled? Please note that the text widget is a standard WordPress widget and it's not something we directly alter.

**Comment by frontenddevguy** [comment]
Hi Alex, I have set up a test site to check on these issues.
Please let me know how I can pm you details.

**Comment by frontenddevguy** [comment]
I have tried adding the shortcode with add Paragraphs disabled and the result is the same

**Comment by frontenddevguy** [comment]
Shortcode issues solved, it depended on featured images being set to output anything.

**Comment by AlexGStapleton** [comment]
Can you please email the details to support@siteorigin.com? Please include a link to this thread for reference.
