### ISSUE TITLE
Page Settings: No Sidebar isn't working when a Post Loop widget in use

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-north#391]
When a Post Loop widget is used on a page, the No Sidebar page layout setting isn't working.

**Comment by AlexGStapleton** [comment]
I've investigated this issue and this issue is actually a general issue in the theme Settings framework. Whatever the last post is that is loaded prior to the `siteorigin_page_setting` check will be the value used.

We have two ways of fixing this:

- Return the default value for any `siteorigin_page_setting` checks done in a post loop
- Always check using the current query id rather than the parent.

The former is likely the way to go as it's simpler and will prevent the Page Settings of a specific post affecting the post loop - that could be problematic if the user has set the post title to hide. Do you want me to do the former, or explore the latter?
