### ISSUE TITLE
Post Loop Pagination: Line breaks are being inserted

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-north#393]
Pagination is vertical when the Post Loop widget is used due to line breaks being inserted after each page link.

**Comment by Misplon** [comment]
@AlexGStapleton I've seen this issue in Corp too. I'm not sure if it's related to the new unit test data with block posts/pages. In Corp the issue is only occurring on page 1, the pagination is normal on page 2.

![About_The_Tests_-_SiteOrigin](https://user-images.githubusercontent.com/789159/88582474-0e5a1580-d04f-11ea-85c3-e1ccc8799c8c.jpg)

**Comment by AlexGStapleton** [comment]
I can't replicate this in Corp, but I can replicate this in North and Vantage. This issue appears to be linked to Yoast. Does this issue occur if you disable that plugin?

**Comment by Misplon** [comment]
I noticed that I can't replicate this issue on the assigned home page. Yes, deactivating Yoast resolves the problem.

**Comment by Misplon** [comment]
I've rolled back to Yoast 1.14.0 and am not seeing a change. I also tried Page Builder 2.9.0 and didn't notice a change.

**Comment by AlexGStapleton** [comment]
I've been looking into this and I'm having a really tricky time working out the exact source of this issue. @Misplon Do you happen to know when the first time you saw this reported?

**Comment by Misplon** [comment]
I can't seem to replicate the issue at the moment. Do you want to close until we get a user report? I found the issue and logged it, a user hasn't reported this problem yet as far as I'm aware.

**Comment by AlexGStapleton** [comment]
I can still replicate this, but I'm okay with waiting until more reports.

Here's how to replicate this:

-Activate Yoast,
- Switch to North (though this can happen with other themes).
- Add a Post Loop to your page.
- Add a Custom HTML widget.

Add the following to that custom HTML widget:

`same line

same line`

- Save.

The above text should be on the same line as the custom HTML widget doesn't add paragraphs, but due to this issue, they're on different lines.

**Comment by Misplon** [comment]
It's strange, I still can't replicate this issue anymore. I'm going to close until we get a report on this. Thanks.
